name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: change directory
      run: cd ljmd-c
    - name: make
      run: make
    - name: make test
      run: make test
